language: python
sudo: required
python:
  - "3.4"
  - "2.7"
  - "pypy"
services:
  - docker
before_install:
  - docker run -d --name dynamodb -p 0:8000 deangiberson/aws-dynamodb-local
  - export DOCKER_PORT=$(docker port dynamodb 8000 | cut -d ':' -f 2)
install: "pip install -Ur requirements.txt"
script: pytest test/
after_script:
  - docker kill dynamodb
  - docker rm -f dynamodb
