version: "3.3"
services:
  dynamodb:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    networks:
      lambda-local:
    ports:
      - "8000:8000"

networks:
  lambda-local:
    external: true
